#!/bin/bash

echo "Installing bundler"
gem install bundler

echo "Installing gems"
bundle check || bundle install
chown -R $USER:$USER .

echo "Configuring webpacker"
yarn upgrade
yarn install --check-files

echo "Creating databases"
bundle exec rails db:reset db:setup db:migrate
bundle exec rails db:create db:schema:load db:test:prepare RAILS_ENV=test
