#!/bin/bash

# CONTAINER_CREATED=$(docker ps --filter "name=iaas-report_server" --format "{{.Names}}")
#
# if [[ "$CONTAINER_CREATED" == "" ]]; then
#     echo "Server was not running. Run it to speed up"
#     docker-compose up -d
# fi
