#!/bin/bash
CONTAINER_CREATED=$(docker ps --filter "name=iaas-report_server" --format "{{.Names}}")

if [[ "$CONTAINER_CREATED" != "" ]]; then
    echo "Server is already running. Use 'docker-compose stop' to stop docker-compose daemon"
    exit 1
fi

if [ -f tmp/pids/server.pid ]; then
  rm tmp/pids/server.pid
fi
docker-compose up
